export const hr_zupanije = [
  "Zagrebačka",
  "Krapinsko-zagorska",
  "Sisačko-moslavačka",
  "Karlovačka",
  "Varaždinska",
  "Koprivničko-križevačka",
  "Bjelovarsko-bilogorska",
  "Primorsko-goranska",
  "Ličko-senjska",
  "Virovitičko-podravska",
  "Požeško-slavonska",
  "Brodsko-posavska",
  "Zadarska",
  "Osječko-baranjska",
  "Šibensko-kninska",
  "Vukovarsko-srijemska",
  "Splitsko-dalmatinska",
  "Istarska",
  "Dubrovačko-neretvanska",
  "Međimurska",
  "Grad Zagreb",
]
