"""mibpg promijenjen u int i min je 1

Revision ID: 06f1f2cc0bd3
Revises: 2edab3409ba2
Create Date: 2025-10-10 14:05:33.610275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f1f2cc0bd3'
down_revision: Union[str, Sequence[str], None] = '2edab3409ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('opgovi', 'identifikacijski_broj_mibpg',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="identifikacijski_broj_mibpg::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('opgovi', 'identifikacijski_broj_mibpg',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using="identifikacijski_broj_mibpg::text")
    # ### end Alembic commands ###
