"""dodavanje tablica kategorije proizvoda i proizvodi

Revision ID: 0b54a103b871
Revises: dea47a04152f
Create Date: 2025-09-10 14:57:22.539262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b54a103b871'
down_revision: Union[str, Sequence[str], None] = 'dea47a04152f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategorije_proizvoda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('datum_izrade', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('datum_zadnje_izmjene', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('naziv'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_kategorije_proizvoda_id'), 'kategorije_proizvoda', ['id'], unique=False)
    op.create_table('proizvodi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=200), nullable=False),
    sa.Column('opis', sa.String(length=500), nullable=True),
    sa.Column('cijena', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('slika_proizvoda', sa.String(length=500), nullable=False),
    sa.Column('proizvod_dostupan', sa.Boolean(), nullable=False),
    sa.Column('mjerna_jedinica', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('datum_izrade', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('datum_zadnje_izmjene', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kategorija_id', sa.Integer(), nullable=False),
    sa.Column('opg_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kategorija_id'], ['kategorije_proizvoda.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['opg_id'], ['opgovi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opg_id', 'slug', name='uq_proizvod_opg_slug')
    )
    op.create_index(op.f('ix_proizvodi_id'), 'proizvodi', ['id'], unique=False)
    op.create_index(op.f('ix_proizvodi_kategorija_id'), 'proizvodi', ['kategorija_id'], unique=False)
    op.create_index(op.f('ix_proizvodi_opg_id'), 'proizvodi', ['opg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proizvodi_opg_id'), table_name='proizvodi')
    op.drop_index(op.f('ix_proizvodi_kategorija_id'), table_name='proizvodi')
    op.drop_index(op.f('ix_proizvodi_id'), table_name='proizvodi')
    op.drop_table('proizvodi')
    op.drop_index(op.f('ix_kategorije_proizvoda_id'), table_name='kategorije_proizvoda')
    op.drop_table('kategorije_proizvoda')
    # ### end Alembic commands ###
