"""dodani stupci za recenzije u tablicu opgovi i opis i slika za kat proizvoda

Revision ID: 13873163522e
Revises: 77a2f2004cff
Create Date: 2025-09-12 14:39:17.193738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13873163522e'
down_revision: Union[str, Sequence[str], None] = '77a2f2004cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kategorije_proizvoda', sa.Column('opis', sa.String(length=500), nullable=True))
    op.add_column('kategorije_proizvoda', sa.Column('slika_kategorije', sa.String(length=500), nullable=True))
    op.add_column('opgovi', sa.Column('prosjecna_ocjena', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('opgovi', sa.Column('broj_recenzija', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opgovi', 'broj_recenzija')
    op.drop_column('opgovi', 'prosjecna_ocjena')
    op.drop_column('kategorije_proizvoda', 'slika_kategorije')
    op.drop_column('kategorije_proizvoda', 'opis')
    # ### end Alembic commands ###
