"""dodane tablice za narudzbu

Revision ID: 2b4fbe7de257
Revises: 69c79f6ede88
Create Date: 2025-09-24 17:42:00.373330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b4fbe7de257'
down_revision: Union[str, Sequence[str], None] = '69c79f6ede88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('narudzbe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broj_narudzbe', sa.String(), nullable=True),
    sa.Column('ime', sa.String(), nullable=False),
    sa.Column('prezime', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefon', sa.String(), nullable=False),
    sa.Column('adresa', sa.String(), nullable=False),
    sa.Column('grad', sa.String(), nullable=False),
    sa.Column('postanski_broj', sa.String(), nullable=False),
    sa.Column('zupanija', sa.String(), nullable=False),
    sa.Column('drzava', sa.String(), nullable=False),
    sa.Column('nacin_placanja', sa.String(), nullable=True),
    sa.Column('nacin_dostave', sa.String(), nullable=True),
    sa.Column('iznos_bez_pdva', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pdv', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dostava', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ukupno', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('datum_izrade', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('korisnik_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['korisnik_id'], ['korisnici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narudzbe_broj_narudzbe'), 'narudzbe', ['broj_narudzbe'], unique=True)
    op.create_index(op.f('ix_narudzbe_id'), 'narudzbe', ['id'], unique=False)
    op.create_table('narudzba_stavke',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tip', sa.String(), nullable=False),
    sa.Column('naziv', sa.String(), nullable=False),
    sa.Column('kolicina', sa.Integer(), nullable=False),
    sa.Column('mjerna_jedinica', sa.String(), nullable=True),
    sa.Column('cijena', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('slika', sa.String(), nullable=True),
    sa.Column('termin_od', sa.DateTime(), nullable=True),
    sa.Column('termin_do', sa.DateTime(), nullable=True),
    sa.Column('narudzba_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['narudzba_id'], ['narudzbe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narudzba_stavke_id'), 'narudzba_stavke', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_narudzba_stavke_id'), table_name='narudzba_stavke')
    op.drop_table('narudzba_stavke')
    op.drop_index(op.f('ix_narudzbe_id'), table_name='narudzbe')
    op.drop_index(op.f('ix_narudzbe_broj_narudzbe'), table_name='narudzbe')
    op.drop_table('narudzbe')
    # ### end Alembic commands ###
