"""dodan status u narudzba stavke, te pr_id i opg_id

Revision ID: 2edab3409ba2
Revises: b0a630c59271
Create Date: 2025-09-29 12:50:19.886866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2edab3409ba2'
down_revision: Union[str, Sequence[str], None] = 'b0a630c59271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('narudzba_stavke', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('narudzba_stavke', sa.Column('proizvod_id', sa.Integer(), nullable=True))
    op.add_column('narudzba_stavke', sa.Column('opg_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_narudzba_stavke_opg_id'), 'narudzba_stavke', ['opg_id'], unique=False)
    op.create_index(op.f('ix_narudzba_stavke_proizvod_id'), 'narudzba_stavke', ['proizvod_id'], unique=False)
    op.create_index(op.f('ix_narudzba_stavke_status'), 'narudzba_stavke', ['status'], unique=False)
    op.create_foreign_key(None, 'narudzba_stavke', 'proizvodi', ['proizvod_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'narudzba_stavke', 'opgovi', ['opg_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'narudzba_stavke', type_='foreignkey')
    op.drop_constraint(None, 'narudzba_stavke', type_='foreignkey')
    op.drop_index(op.f('ix_narudzba_stavke_status'), table_name='narudzba_stavke')
    op.drop_index(op.f('ix_narudzba_stavke_proizvod_id'), table_name='narudzba_stavke')
    op.drop_index(op.f('ix_narudzba_stavke_opg_id'), table_name='narudzba_stavke')
    op.drop_column('narudzba_stavke', 'opg_id')
    op.drop_column('narudzba_stavke', 'proizvod_id')
    op.drop_column('narudzba_stavke', 'status')
    # ### end Alembic commands ###
