"""dodana tablica za kosaricu

Revision ID: 69c79f6ede88
Revises: bcdc9fd78cbe
Create Date: 2025-09-23 17:29:54.742261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c79f6ede88'
down_revision: Union[str, Sequence[str], None] = 'bcdc9fd78cbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kosarica_stavke',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kolicina', sa.Integer(), nullable=False),
    sa.Column('termin_od', sa.String(length=50), nullable=True),
    sa.Column('termin_do', sa.String(length=50), nullable=True),
    sa.Column('cijena', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mjerna_jedinica', sa.String(length=50), nullable=False),
    sa.Column('datum_izrade', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('datum_zadnje_izmjene', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('korisnik_id', sa.Integer(), nullable=False),
    sa.Column('proizvod_id', sa.Integer(), nullable=True),
    sa.Column('usluga_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(proizvod_id IS NOT NULL AND usluga_id IS NULL) OR (proizvod_id IS NULL AND usluga_id IS NOT NULL)', name='ck_kos_xor_proizvod_usluga'),
    sa.ForeignKeyConstraint(['korisnik_id'], ['korisnici.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proizvod_id'], ['proizvodi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usluga_id'], ['usluge.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('korisnik_id', 'proizvod_id', name='uq_kos_proizvod_po_korisniku'),
    sa.UniqueConstraint('korisnik_id', 'usluga_id', 'termin_od', 'termin_do', name='uq_kos_usluga_termin_po_korisniku')
    )
    op.create_index('ix_kos_korisnik_tip', 'kosarica_stavke', ['korisnik_id', 'proizvod_id', 'usluga_id'], unique=False)
    op.create_index(op.f('ix_kosarica_stavke_korisnik_id'), 'kosarica_stavke', ['korisnik_id'], unique=False)
    op.create_index(op.f('ix_kosarica_stavke_proizvod_id'), 'kosarica_stavke', ['proizvod_id'], unique=False)
    op.create_index(op.f('ix_kosarica_stavke_usluga_id'), 'kosarica_stavke', ['usluga_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kosarica_stavke_usluga_id'), table_name='kosarica_stavke')
    op.drop_index(op.f('ix_kosarica_stavke_proizvod_id'), table_name='kosarica_stavke')
    op.drop_index(op.f('ix_kosarica_stavke_korisnik_id'), table_name='kosarica_stavke')
    op.drop_index('ix_kos_korisnik_tip', table_name='kosarica_stavke')
    op.drop_table('kosarica_stavke')
    # ### end Alembic commands ###
