"""dodavanje tablica kategorije usluga i usluge

Revision ID: 77a2f2004cff
Revises: 876c0ce0d7c4
Create Date: 2025-09-11 16:23:43.652928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a2f2004cff'
down_revision: Union[str, Sequence[str], None] = '876c0ce0d7c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategorije_usluga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('datum_izrade', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('datum_zadnje_izmjene', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_kategorije_usluga_id'), 'kategorije_usluga', ['id'], unique=False)
    op.create_table('usluge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=200), nullable=False),
    sa.Column('opis', sa.String(length=500), nullable=True),
    sa.Column('cijena', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('slika_usluge', sa.String(length=500), nullable=True),
    sa.Column('usluga_dostupna', sa.Boolean(), nullable=False),
    sa.Column('mjerna_jedinica', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('datum_izrade', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('datum_zadnje_izmjene', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kategorija_id', sa.Integer(), nullable=False),
    sa.Column('opg_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kategorija_id'], ['kategorije_usluga.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['opg_id'], ['opgovi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opg_id', 'slug', name='uq_usluga_opg_slug')
    )
    op.create_index(op.f('ix_usluge_id'), 'usluge', ['id'], unique=False)
    op.create_index(op.f('ix_usluge_kategorija_id'), 'usluge', ['kategorija_id'], unique=False)
    op.create_index(op.f('ix_usluge_opg_id'), 'usluge', ['opg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usluge_opg_id'), table_name='usluge')
    op.drop_index(op.f('ix_usluge_kategorija_id'), table_name='usluge')
    op.drop_index(op.f('ix_usluge_id'), table_name='usluge')
    op.drop_table('usluge')
    op.drop_index(op.f('ix_kategorije_usluga_id'), table_name='kategorije_usluga')
    op.drop_table('kategorije_usluga')
    # ### end Alembic commands ###
