"""dodana tablica za recenzije

Revision ID: 81bdf0100a64
Revises: 13873163522e
Create Date: 2025-09-14 22:25:37.619474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81bdf0100a64'
down_revision: Union[str, Sequence[str], None] = '13873163522e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recenzije',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocjena', sa.Integer(), nullable=False),
    sa.Column('komentar', sa.Text(), nullable=True),
    sa.Column('datum_izrade', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('datum_zadnje_izmjene', sa.DateTime(), nullable=True),
    sa.Column('opg_id', sa.Integer(), nullable=False),
    sa.Column('korisnik_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['korisnik_id'], ['korisnici.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opg_id'], ['opgovi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opg_id', 'korisnik_id', name='uq_recenzija_opg_korisnik')
    )
    op.create_index(op.f('ix_recenzije_id'), 'recenzije', ['id'], unique=False)
    op.create_index(op.f('ix_recenzije_opg_id'), 'recenzije', ['opg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recenzije_opg_id'), table_name='recenzije')
    op.drop_index(op.f('ix_recenzije_id'), table_name='recenzije')
    op.drop_table('recenzije')
    # ### end Alembic commands ###
