"""s brisanjem profila obrisi i recenziju

Revision ID: 85463f09734c
Revises: 81bdf0100a64
Create Date: 2025-09-16 14:15:42.393892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85463f09734c'
down_revision: Union[str, Sequence[str], None] = '81bdf0100a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recenzije', 'korisnik_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('recenzije_korisnik_id_fkey'), 'recenzije', type_='foreignkey')
    op.create_foreign_key(None, 'recenzije', 'korisnici', ['korisnik_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recenzije', type_='foreignkey')
    op.create_foreign_key(op.f('recenzije_korisnik_id_fkey'), 'recenzije', 'korisnici', ['korisnik_id'], ['id'], ondelete='SET NULL')
    op.alter_column('recenzije', 'korisnik_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
