"""slika_proizvoda nullable

Revision ID: 876c0ce0d7c4
Revises: 0b54a103b871
Create Date: 2025-09-10 22:06:59.553540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876c0ce0d7c4'
down_revision: Union[str, Sequence[str], None] = '0b54a103b871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proizvodi', 'slika_proizvoda',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proizvodi', 'slika_proizvoda',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
