"""s brisanjem korisnickog profila narudzba je anonimna ali ostaje

Revision ID: 95cb4b339b31
Revises: 2b4fbe7de257
Create Date: 2025-09-24 20:30:45.326618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95cb4b339b31'
down_revision: Union[str, Sequence[str], None] = '2b4fbe7de257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_narudzbe_korisnik_id'), 'narudzbe', ['korisnik_id'], unique=False)
    op.drop_constraint(op.f('narudzbe_korisnik_id_fkey'), 'narudzbe', type_='foreignkey')
    op.create_foreign_key(None, 'narudzbe', 'korisnici', ['korisnik_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'narudzbe', type_='foreignkey')
    op.create_foreign_key(op.f('narudzbe_korisnik_id_fkey'), 'narudzbe', 'korisnici', ['korisnik_id'], ['id'])
    op.drop_index(op.f('ix_narudzbe_korisnik_id'), table_name='narudzbe')
    # ### end Alembic commands ###
