"""dodana usluga id u narudzbastavke

Revision ID: b0a630c59271
Revises: 95cb4b339b31
Create Date: 2025-09-26 13:07:31.831405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0a630c59271'
down_revision: Union[str, Sequence[str], None] = '95cb4b339b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('narudzba_stavke', sa.Column('usluga_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_narudzba_stavke_usluga_id'), 'narudzba_stavke', ['usluga_id'], unique=False)
    op.create_foreign_key(None, 'narudzba_stavke', 'usluge', ['usluga_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'narudzba_stavke', type_='foreignkey')
    op.drop_index(op.f('ix_narudzba_stavke_usluga_id'), table_name='narudzba_stavke')
    op.drop_column('narudzba_stavke', 'usluga_id')
    # ### end Alembic commands ###
