"""dodavanje constrainta za datume i brisanje tj t

Revision ID: bcdc9fd78cbe
Revises: be4653f4ee78
Create Date: 2025-09-21 14:13:03.848051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcdc9fd78cbe'
down_revision: Union[str, Sequence[str], None] = 'be4653f4ee78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opgovi_tjedna_raspolozivost_opg_id'), table_name='opgovi_tjedna_raspolozivost')
    op.drop_table('opgovi_tjedna_raspolozivost')
    op.create_index('ix_raspolozivost_opg_datum', 'opgovi_raspolozivost_po_datumu', ['opg_id', 'datum'], unique=False)
    op.create_unique_constraint('uq_opg_datum_poc_kraj', 'opgovi_raspolozivost_po_datumu', ['opg_id', 'datum', 'pocetno_vrijeme', 'zavrsno_vrijeme'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_opg_datum_poc_kraj', 'opgovi_raspolozivost_po_datumu', type_='unique')
    op.drop_index('ix_raspolozivost_opg_datum', table_name='opgovi_raspolozivost_po_datumu')
    op.create_table('opgovi_tjedna_raspolozivost',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dan_u_tjednu', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pocetno_vrijeme', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('zavrsno_vrijeme', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('odabrano', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('naslov', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('opg_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['opg_id'], ['opgovi.id'], name=op.f('opgovi_tjedna_raspolozivost_opg_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('opgovi_tjedna_raspolozivost_pkey')),
    sa.UniqueConstraint('opg_id', 'dan_u_tjednu', name=op.f('uq_danutjednu_rule'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_opgovi_tjedna_raspolozivost_opg_id'), 'opgovi_tjedna_raspolozivost', ['opg_id'], unique=False)
    # ### end Alembic commands ###
