"""dodani modeli za raspolozivost opgova i mj

Revision ID: be4653f4ee78
Revises: 85463f09734c
Create Date: 2025-09-19 14:17:11.246590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be4653f4ee78'
down_revision: Union[str, Sequence[str], None] = '85463f09734c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opgovi_raspolozivost_po_datumu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('pocetno_vrijeme', sa.Integer(), nullable=False),
    sa.Column('zavrsno_vrijeme', sa.Integer(), nullable=False),
    sa.Column('naslov', sa.String(length=200), nullable=True),
    sa.Column('opg_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opg_id'], ['opgovi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opgovi_raspolozivost_po_datumu_opg_id'), 'opgovi_raspolozivost_po_datumu', ['opg_id'], unique=False)
    op.create_table('opgovi_tjedna_raspolozivost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dan_u_tjednu', sa.Integer(), nullable=False),
    sa.Column('pocetno_vrijeme', sa.Integer(), nullable=False),
    sa.Column('zavrsno_vrijeme', sa.Integer(), nullable=False),
    sa.Column('odabrano', sa.Boolean(), nullable=False),
    sa.Column('naslov', sa.String(length=200), nullable=True),
    sa.Column('opg_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opg_id'], ['opgovi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opg_id', 'dan_u_tjednu', name='uq_danutjednu_rule')
    )
    op.create_index(op.f('ix_opgovi_tjedna_raspolozivost_opg_id'), 'opgovi_tjedna_raspolozivost', ['opg_id'], unique=False)
    op.add_column('usluge', sa.Column('trajanje_po_mjernoj_jedinici', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usluge', 'trajanje_po_mjernoj_jedinici')
    op.drop_index(op.f('ix_opgovi_tjedna_raspolozivost_opg_id'), table_name='opgovi_tjedna_raspolozivost')
    op.drop_table('opgovi_tjedna_raspolozivost')
    op.drop_index(op.f('ix_opgovi_raspolozivost_po_datumu_opg_id'), table_name='opgovi_raspolozivost_po_datumu')
    op.drop_table('opgovi_raspolozivost_po_datumu')
    # ### end Alembic commands ###
