"""init schema

Revision ID: dea47a04152f
Revises: 
Create Date: 2025-09-05 17:01:51.759797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dea47a04152f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('korisnici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(length=100), nullable=True),
    sa.Column('prezime', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('korisnicko_ime', sa.String(length=50), nullable=False),
    sa.Column('lozinka', sa.String(length=255), nullable=False),
    sa.Column('tip_korisnika', sa.Enum('kupac', 'opg', name='tipkorisnika'), nullable=False),
    sa.Column('broj_telefona', sa.String(length=20), nullable=True),
    sa.Column('datum_pridruzivanja', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('datum_zadnje_izmjene', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broj_telefona'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('korisnicko_ime')
    )
    op.create_index(op.f('ix_korisnici_id'), 'korisnici', ['id'], unique=False)
    op.create_table('korisnicki_profili',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slika_profila', sa.String(length=255), nullable=True),
    sa.Column('drzava', sa.String(length=100), nullable=True),
    sa.Column('zupanija', sa.String(length=100), nullable=True),
    sa.Column('grad', sa.String(length=100), nullable=True),
    sa.Column('postanski_broj', sa.String(length=10), nullable=True),
    sa.Column('adresa', sa.String(length=255), nullable=True),
    sa.Column('datum_pridruzivanja', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('datum_zadnje_izmjene', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('korisnik_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['korisnik_id'], ['korisnici.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('korisnik_id')
    )
    op.create_index(op.f('ix_korisnicki_profili_id'), 'korisnicki_profili', ['id'], unique=False)
    op.create_table('kupci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum_pridruzivanja', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('datum_zadnje_izmjene', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('korisnik_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['korisnik_id'], ['korisnici.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('korisnik_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_kupci_id'), 'kupci', ['id'], unique=False)
    op.create_table('opgovi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=150), nullable=True),
    sa.Column('opis', sa.String(length=500), nullable=True),
    sa.Column('verificiran', sa.Boolean(), nullable=True),
    sa.Column('identifikacijski_broj_mibpg', sa.String(length=50), nullable=False),
    sa.Column('datum_pridruzivanja', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('datum_zadnje_izmjene', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('korisnik_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['korisnik_id'], ['korisnici.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifikacijski_broj_mibpg'),
    sa.UniqueConstraint('korisnik_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_opgovi_id'), 'opgovi', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opgovi_id'), table_name='opgovi')
    op.drop_table('opgovi')
    op.drop_index(op.f('ix_kupci_id'), table_name='kupci')
    op.drop_table('kupci')
    op.drop_index(op.f('ix_korisnicki_profili_id'), table_name='korisnicki_profili')
    op.drop_table('korisnicki_profili')
    op.drop_index(op.f('ix_korisnici_id'), table_name='korisnici')
    op.drop_table('korisnici')
    # ### end Alembic commands ###
